// ============================================================
//  WEB MODE — THE ZIP
//  Ships the user's component plus the motion, as files they can drop into a
//  project: their source untouched, a stylesheet of baked @keyframes, and an
//  optional ~1KB script for the hover interaction.
//
//  The animation is CSS. The script only reaches for the animations CSS
//  already created (element.getAnimations()) and eases their playbackRate —
//  so if it never loads, the component still animates. That is the whole
//  reason for doing it this way rather than driving frames from JS.
// ============================================================

import JSZip from 'jszip';
import { bakeCss, STAGE_CLASS, type BakeOpts } from './webKeyframes';

export interface ExportOpts extends BakeOpts {
  /** The user's source, exactly as they pasted it. */
  source: string;
  /** Their stylesheet, if any. */
  css: string;
  hover: HoverOpts | null;
}

export interface HoverOpts {
  /** Milliseconds to reach a standstill (and to come back). */
  duration: number;
  /** The scene easing, sampled — works for beziers and physics curves alike. */
  curve: (t: number) => number;
}

/** Sample a curve into a lookup table the runtime can lerp without maths. */
function sampleCurve(fn: (t: number) => number, n = 24): number[] {
  const out: number[] = [];
  for (let i = 0; i <= n; i++) out.push(Math.round(fn(i / n) * 1e4) / 1e4);
  return out;
}

const RUNTIME = (lut: number[], duration: number) => `// Motion Studio — hover interaction (optional).
// The motion itself is CSS. This only eases the playback rate of the
// animations the stylesheet already started, so without this file the
// component still animates — it just stops instantly on hover instead of
// gliding to a halt.
(function () {
  var EASE = ${JSON.stringify(lut)};
  var MS = ${duration};

  // The scene's easing curve, sampled at author time and lerped here.
  function ease(t) {
    if (t <= 0) return EASE[0];
    if (t >= 1) return EASE[EASE.length - 1];
    var x = t * (EASE.length - 1);
    var i = Math.floor(x);
    return EASE[i] + (EASE[i + 1] - EASE[i]) * (x - i);
  }

  function attach(stage) {
    if (stage.__msx) return;
    stage.__msx = true;

    var raf = 0;
    var rate = 1;        // where we are
    var target = 1;      // where we're heading
    var from = 1;
    var start = 0;

    // The animated elements are wherever the selectors pointed — usually
    // nested well below the stage, not its direct children. subtree:true is
    // the only thing that finds them.
    function anims() {
      if (stage.getAnimations) return stage.getAnimations({ subtree: true });
      var list = [];
      var all = stage.querySelectorAll('*');
      for (var i = 0; i < all.length; i++) {
        var a = all[i].getAnimations ? all[i].getAnimations() : [];
        for (var j = 0; j < a.length; j++) list.push(a[j]);
      }
      return list;
    }

    function apply(r) {
      var list = anims();
      // Exactly 0 is a real standstill: playState stays 'running', so setting
      // the rate back resumes from where it stopped, with no seek and no jump.
      for (var i = 0; i < list.length; i++) list[i].playbackRate = r;
    }

    function tick(now) {
      var t = Math.min(1, (now - start) / MS);
      rate = from + (target - from) * ease(t);
      apply(rate);
      if (t < 1) raf = requestAnimationFrame(tick);
      else raf = 0;
    }

    function to(v) {
      if (target === v && !raf) return;
      target = v;
      from = rate;
      start = performance.now();
      if (!raf) raf = requestAnimationFrame(tick);
    }

    stage.addEventListener('mouseenter', function () { to(0); });
    stage.addEventListener('mouseleave', function () { to(1); });
    // Keyboard and touch users get the same affordance.
    stage.addEventListener('focusin', function () { to(0); });
    stage.addEventListener('focusout', function () { to(1); });
  }

  function init() {
    var stages = document.querySelectorAll('.${STAGE_CLASS}');
    for (var i = 0; i < stages.length; i++) attach(stages[i]);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
`;

const README = (o: ExportOpts, hasHover: boolean) => `# ${o.template.meta.name} — animated component

Generated by Motion Studio.

## Files

| File | What it is |
|---|---|
| \`Component.jsx\` | your source, unchanged |
| \`MotionStage.jsx\` | the wrapper that carries the \`.${STAGE_CLASS}\` class |
| \`motion.css\` | the animation — baked \`@keyframes\`, one per layer |
${o.css.trim() ? '| `component.css` | your own stylesheet |\n' : ''}${hasHover ? `| \`motion.js\` | hover interaction (optional — see below) |\n` : ''}
## Use

\`\`\`jsx
import MotionStage from './MotionStage';
import './motion.css';${o.css.trim() ? "\nimport './component.css';" : ''}

<MotionStage />
\`\`\`

${hasHover ? `## Hover

\`motion.js\` eases the animation to a stop on hover and back on leave, over
${o.hover!.duration}ms on the scene's easing curve. Load it once, anywhere:

\`\`\`html
<script src="./motion.js" defer></script>
\`\`\`

It is **optional**. The animation is pure CSS; the script only adjusts the
playback rate of animations that already exist. Without it the component still
animates — it just doesn't respond to the pointer.

` : ''}## Notes

- Motion is \`@keyframes\`, sampled from the template. No runtime, no
  dependency, no build step.
- The scene's easing is already baked into where the keyframes fall, which is
  why the rules say \`linear\`. Don't add a timing function — it would apply the
  curve twice.
- The loop is seamless: 0% and 100% are the same pose by construction.
- \`prefers-reduced-motion: reduce\` disables the animation.
${o.mode === 'own' ? `- Layout mode was **own**: the animated elements are positioned absolutely from
  the stage centre, and the stage is a fixed ${o.canvas.w}×${o.canvas.h} box.
  Whatever layout they had is replaced by the template's.` : `- Layout mode was **decorate**: your layout is untouched; the keyframes only
  carry the template's motion, relative to each element's resting position.`}
`;

const WRAPPER = (hasUserCss: boolean, userCss: string) => `import Component from './Component';
import './motion.css';${hasUserCss ? "\nimport './component.css';" : ''}

// The animation targets \`.${STAGE_CLASS} > …\` by structural position, so this
// wrapper is what the generated selectors hang off. Keep the class.
export default function MotionStage() {
  return (
    <div className="${STAGE_CLASS}">
      <Component />
    </div>
  );
}
`;

export async function buildZip(o: ExportOpts): Promise<Blob> {
  const zip = new JSZip();
  const hasHover = !!o.hover;

  zip.file('motion.css', bakeCss(o));
  zip.file('Component.jsx', o.source.trim().startsWith('<')
    // A bare JSX expression isn't a module — wrap it the same way the preview
    // does, so the file is importable.
    ? `export default function Component() {\n  return (\n${o.source.trim().replace(/;\s*$/, '')}\n  );\n}\n`
    : `${o.source.trim()}\n`);
  zip.file('MotionStage.jsx', WRAPPER(!!o.css.trim(), o.css));
  if (o.css.trim()) zip.file('component.css', `${o.css.trim()}\n`);
  if (o.hover) zip.file('motion.js', RUNTIME(sampleCurve(o.hover.curve), o.hover.duration));
  zip.file('README.md', README(o, hasHover));

  return zip.generateAsync({ type: 'blob' });
}
